-- Generated by docs/addon/tools/gen_icons.py in the wow-auction repository. Do not edit by hand.
-- Glyphs: Phosphor Icons (MIT), Media/LICENSE-Phosphor.txt.
local _, GC = ...
GC.Kit = GC.Kit or {}
GC.Kit.Icons = {
  file = "Interface\\AddOns\\GoldCap\\Media\\icons.png", cell = 32, columns = 16, size = 512,
  index = {
    deals = 0,
    sell = 1,
    sold = 2,
    buy = 3,
    gear = 4,
    refresh = 5,
    search = 6,
    close = 7,
    check = 8,
    warning = 9,
    info = 10,
    clock = 11,
    filter = 12,
    star = 13,
    bag = 14,
    caretUp = 15,
    caretDown = 16,
    caretLeft = 17,
    caretRight = 18,
    plus = 19,
    minus = 20,
    mail = 21,
    trend = 22,
    lightning = 23,
  },
}
