local helper = require("spec.spec_helper")

-- The files UI/Kit draws ship in Media/, and the icon index generated by
-- docs/addon/tools/gen_icons.py (wow-auction) points inside its atlas.
local function exists(path)
  local file = io.open(path, "rb")
  if file then file:close() return true end
  return false
end

describe("kit media", function()
  it("ships the Fira faces, their licence, the icon atlas and the kit's textures", function()
    for _, name in ipairs({ "FiraSans-Medium.ttf", "FiraSans-SemiBold.ttf", "FiraSans-Bold.ttf",
      "FiraSansCondensed-Bold.ttf", "FiraSansCondensed-ExtraBold.ttf", "FiraMono-Medium.ttf",
      "FiraMono-Bold.ttf", "OFL-Fira.txt", "icons.png", "LICENSE-Phosphor.txt", "shadow.png",
      "card.png", "ring.png", "card_left.png", "card_right.png" }) do
      assert.is_true(exists("GoldCap/Media/" .. name), name .. " is missing")
    end
  end)

  it("indexes every icon inside the atlas, one cell each", function()
    local GC = helper.loadModule("UI/Kit/Icons.lua")
    local icons = GC.Kit.Icons
    local cells = (icons.size / icons.cell) ^ 2
    local seen = {}
    for name, index in pairs(icons.index) do
      assert.is_true(index >= 0 and index < cells, name .. " is outside the atlas")
      assert.is_nil(seen[index], name .. " shares a cell with " .. tostring(seen[index]))
      seen[index] = name
    end
  end)

  it("has the icons the rail, the title bar, the Sold tab and the buttons ask for", function()
    local GC = helper.loadModule("UI/Kit/Icons.lua")
    for _, name in ipairs({ "deals", "sell", "sold", "buy", "gear", "close", "trend", "search", "mail",
      "caretDown", "caretUp" }) do
      assert.is_number(GC.Kit.Icons.index[name], name)
    end
  end)
end)
