describe("Grouped Sell wiring", function()
  local function source()
    local f = assert(io.open("GoldCap/UI/SellFrame.lua", "r"))
    local text = f:read("*a")
    f:close()
    return text
  end

  it("composes positions, remembers expansion by position key, and uses the grouped columns", function()
    local text = source()
    assert.is_truthy(text:find("GC.SellPositions.Build", 1, true))
    assert.is_truthy(text:find("expanded[position.positionKey]", 1, true))
    assert.is_truthy(text:find('{ key = "cost", w = 82, num = true }', 1, true))
    assert.is_truthy(text:find('{ key = "listed", w = 72, num = true }', 1, true))
    assert.is_truthy(text:find('{ key = "market", w = 72, num = true, optional = true }', 1, true))
    assert.is_truthy(text:find('{ key = "profit", w = 76, num = true, bold = true }', 1, true))
    assert.is_truthy(text:find('{ key = "status", w = 92 }', 1, true))
    assert.is_nil(text:find("BuildRow", 1, true))
    assert.is_nil(text:find("OrphanLotRows", 1, true))
  end)

  it("uses one owned-auctions refresh followed by the sequential quote walk", function()
    local text = source()
    local refresh = assert(text:match("function GC%.Sell%.Refresh%(%)(.-)function GC%.Sell%.Reset"))
    assert.is_truthy(refresh:find("requestOwnedAuctions()", 1, true))
    assert.is_truthy(refresh:find("onOwnedAuctionsReady", 1, true))
    assert.is_truthy(text:find("Refreshing listings…", 1, true))
    assert.is_truthy(text:find("Pricing %d/%d…", 1, true))
  end)
end)
